### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by zakiyousufi**
### In this PR I have created the greeting API using ruby languge and rails server and UI js languge and ract library
[project UI](https://github.com/zakiyousufi/hello-react-front_end/pull/1)

**_Note: I have repeated the module Becouse of this I requisting review in this PR_**

### CODE REVIEW

**Comment by mcrd25** [comment]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your board.

## Invalid Code Review Request

You have submitted a project, that does not contain a screenshot of the current state of the Kanban Board at the time of review request which is seen as a requirement [here](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by zakiyousufi** [comment]
@mcrd25  Hello 
I thinks you have review this by mistake becuse its belongs to the hello react reals project

**Review by rloterh — COMMENTED** [review]
Hi Yousufi, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- You have submitted a project, that has incorrect gitflow/ GitHub flow. Kindly note that the Pull Request for this activity should flow **from feature into development**. Kindly use the correct gitflow and request another code review.
- Also ensure to include the link of the frontend in your ReadMe, and the vice versa.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by zakiyousufi** [comment]
@rloterh  Hello  
Did you read the PR discribtion

**Pull request closed without merging**
